name: app
description: "Template app"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  bloc_event_status: ^1.1.1
  bloc_presentation: ^1.1.1
  dart_mappable: ^4.5.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  provider: ^6.1.2
  template_domain: 0.0.1
  template_fake_data: 0.0.1

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
