name: template
description: "Template app"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  bloc_event_status: ^1.1.1
  bloc_presentation: ^1.1.2
  dart_mappable: ^4.6.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  provider: ^6.1.5

dev_dependencies:
  build_runner: ^2.11.1
  dart_mappable_builder: ^4.6.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
