name: template_fake_data
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  dart_mappable: ^4.5.0
  template_domain: 0.0.1

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  test: ^1.25.6
  very_good_analysis: ^7.0.0
